services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo-data:/data/db]

  app:
    build: .
    ports: ["8080:8080"]
    environment:
      MONGO_URL: mongodb://mongo:27017/ecommerce
      USE_ETHEREAL: "true"
      JWT_SECRET: "changeme"
      RESET_SECRET: "changeme2"
      BASE_URL: "http://localhost:8080"
    depends_on: [mongo]

volumes:
  mongo-data:
